### ISSUE TITLE
The IMU model and the control method

### ISSUE THREAD

**Issue by dongdongbh** [uzh-rpg/learned_inertial_model_odometry#2]
Excellent work! I have a few questions about the project.

* Which IMU model is used?
* Is the control method based on the reinforcement learning method described in paper [33](`Autonomous drone racing with deep reinforcement learning`)?
* Paper [33] states that "executing the trajectory results in large tracking errors." How do you deal with this issue?

**Comment by gcioffi** [comment]
Hi,

- the imu model is the same as the one used here: https://arxiv.org/pdf/2007.01867.pdf
- The control method is an extension of [33]. We will have soon a publication related to it.
